-- MySQL Script generated by MySQL Workbench
-- Mon Sep 21 18:02:16 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco_campo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_campo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_campo` DEFAULT CHARACTER SET utf8 ;
USE `banco_campo` ;

-- -----------------------------------------------------
-- Table `banco_campo`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_campo`.`Produto` (
  `codp` BIGINT(20) NOT NULL,
  `nome` VARCHAR(32) NULL,
  `preco_venda` DECIMAL(7,2) NULL,
  `qtde_estoque` INT NULL DEFAULT 0,
  `lote` VARCHAR(45) NOT NULL DEFAULT '1',
  `preco_custo` DECIMAL(7,2) NULL,
  `status` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`codp`, `lote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_campo`.`Comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_campo`.`Comanda` (
  `codc` INT NOT NULL AUTO_INCREMENT,
  `data_venda` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `valor_total` DECIMAL(7,2) NOT NULL,
  `nick` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`codc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_campo`.`ItemVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_campo`.`ItemVenda` (
  `preco_vendido` DECIMAL(7,2) NOT NULL,
  `qtde` INT NOT NULL,
  `codc` INT NOT NULL,
  `codp` BIGINT(20) NOT NULL,
  `lote` VARCHAR(45) NOT NULL DEFAULT '1',
  PRIMARY KEY (`codc`, `codp`, `lote`),
  INDEX `fk_ItemVenda_Produto_idx` (`codp` ASC, `lote` ASC) VISIBLE,
  CONSTRAINT `fk_ItemVenda_Produto`
    FOREIGN KEY (`codp` , `lote`)
    REFERENCES `banco_campo`.`Produto` (`codp` , `lote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemVenda_Comanda`
    FOREIGN KEY (`codc`)
    REFERENCES `banco_campo`.`Comanda` (`codc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_campo`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_campo`.`Pagamento` (
  `codpag` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(7,2) NOT NULL,
  `data` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `tipo_pagamento` VARCHAR(30) NOT NULL,
  `codc` INT NOT NULL,
  PRIMARY KEY (`codpag`),
  INDEX `fk_Pagamento_Venda1_idx` (`codc` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_Comanda`
    FOREIGN KEY (`codc`)
    REFERENCES `banco_campo`.`Comanda` (`codc`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_campo`.`Ativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_campo`.`Ativo` (
  `coda` INT NOT NULL AUTO_INCREMENT,
  `qtde` INT NOT NULL,
  `valor` DECIMAL(7,2) NOT NULL,
  `nome` VARCHAR(32) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`coda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_campo`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_campo`.`Usuario` (
  `codu` INT NOT NULL,
  `nome` VARCHAR(32) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `tipo` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`codu`, `senha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_campo`.`SaldoAtivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_campo`.`SaldoAtivo` (
  `codsa` INT NOT NULL AUTO_INCREMENT,
  `data_hora` DATETIME NOT NULL,
  `qtde` INT NOT NULL,
  `codu` INT NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `coda` INT NOT NULL,
  PRIMARY KEY (`codsa`),
  INDEX `fk_SaldoAtivo_Usuario_idx` (`codu` ASC) VISIBLE,
  INDEX `fk_SaldoAtivo_Ativo_idx` (`coda` ASC) VISIBLE,
  CONSTRAINT `fk_SaldoAtivo_Usuario`
    FOREIGN KEY (`codu`)
    REFERENCES `banco_campo`.`Usuario` (`codu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SaldoAtivo_Ativo`
    FOREIGN KEY (`coda`)
    REFERENCES `banco_campo`.`Ativo` (`coda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_campo`.`SaldoEstoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_campo`.`SaldoEstoque` (
  `codse` INT NOT NULL AUTO_INCREMENT,
  `qtde` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `codp` BIGINT(20) NOT NULL,
  `codu` INT NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `lote` VARCHAR(45) NOT NULL DEFAULT '1',
  PRIMARY KEY (`codse`),
  INDEX `fk_SaldoEstoque_Usuario_idx` (`codu` ASC) VISIBLE,
  INDEX `fk_SaldoEstoque_Produto_idx` (`codp` ASC, `lote` ASC) VISIBLE,
  CONSTRAINT `fk_SaldoEstoque_Usuario`
    FOREIGN KEY (`codu`)
    REFERENCES `banco_campo`.`Usuario` (`codu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SaldoEstoque_Produto`
    FOREIGN KEY (`codp` , `lote`)
    REFERENCES `banco_campo`.`Produto` (`codp` , `lote`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `banco_campo`;

DELIMITER $$
USE `banco_campo`$$
CREATE DEFINER = CURRENT_USER TRIGGER `banco_campo`.`Produto_BEFORE_INSERT` BEFORE INSERT ON `Produto` FOR EACH ROW
BEGIN
	IF NEW.preco_custo < 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Erro: O preço do produto não pode ser negativo!';
	END IF;
    
    IF NEW.preco_venda < 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Erro: O preço do produto não pode ser negativo!';
	END IF;

    IF NEW.qtde_estoque < 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Erro: A quantia em estoque não pode ser negativa!';
    END IF;
    
    IF NEW.nome REGEXP '^[0-9]+$' THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Erro: O nome do produto não pode conter apenas números!';
    END IF;
END$$

USE `banco_campo`$$
CREATE DEFINER = CURRENT_USER TRIGGER `banco_campo`.`Produto_BEFORE_UPDATE` BEFORE UPDATE ON `Produto` FOR EACH ROW
BEGIN
    IF NEW.qtde_estoque < 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Erro: A quantia em estoque não pode ser negativa!';
    END IF;
END$$

USE `banco_campo`$$
CREATE DEFINER = CURRENT_USER TRIGGER `banco_campo`.`Comanda_BEFORE_INSERT` BEFORE INSERT ON `Comanda` FOR EACH ROW
BEGIN
IF NEW.data_venda > NOW() THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'Erro: A data da venda não pode ser uma data futura.';
    END IF;

END$$

USE `banco_campo`$$
CREATE DEFINER = CURRENT_USER TRIGGER `banco_campo`.`Comanda_BEFORE_UPDATE` BEFORE UPDATE ON `Comanda` FOR EACH ROW
BEGIN
IF NEW.valor_total < 0 THEN SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'Erro: O valor total da comanda não pode ser modificado para um valor negativo.';
END IF;
IF NEW.data_venda > NOW() THEN SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'Erro: Não é permitido alterar a data da comanda para uma data futura.';
END IF;
END$$

USE `banco_campo`$$
CREATE DEFINER = CURRENT_USER TRIGGER `banco_campo`.`ItemVenda_AFTER_INSERT` AFTER INSERT ON `ItemVenda` FOR EACH ROW
BEGIN
UPDATE Comanda
    SET valor_total = (
        SELECT COALESCE(SUM(preco_vendido * qtde), 0)
        FROM ItemVenda
        WHERE codc = NEW.codc
    )
    WHERE codc = NEW.codc;
END$$

USE `banco_campo`$$
CREATE DEFINER = CURRENT_USER TRIGGER `banco_campo`.`ItemVenda_AFTER_UPDATE` AFTER UPDATE ON `ItemVenda` FOR EACH ROW
BEGIN
UPDATE Comanda
    SET valor_total = (
        SELECT COALESCE(SUM(preco_vendido * qtde), 0)
        FROM ItemVenda
        WHERE codc = NEW.codc
    )
    WHERE codc = NEW.codc;

    IF OLD.codc <> NEW.codc THEN
        UPDATE Comanda
        SET valor_total = (
            SELECT COALESCE(SUM(preco_vendido * qtde), 0)
            FROM ItemVenda
            WHERE codc = OLD.codc
        )
        WHERE codc = OLD.codc;
    END IF;
END$$

USE `banco_campo`$$
CREATE DEFINER = CURRENT_USER TRIGGER `banco_campo`.`ItemVenda_AFTER_DELETE` AFTER DELETE ON `ItemVenda` FOR EACH ROW
BEGIN
UPDATE Comanda
    SET valor_total = (
        SELECT COALESCE(SUM(preco_vendido * qtde), 0)
        FROM ItemVenda
        WHERE codc = OLD.codc
    )
    WHERE codc = OLD.codc;
END$$

USE `banco_campo`$$
CREATE DEFINER = CURRENT_USER TRIGGER `banco_campo`.`Pagamento_BEFORE_INSERT` BEFORE INSERT ON `Pagamento` FOR EACH ROW
BEGIN
IF NEW.valor <= 0 THEN SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'Erro: O valor do pagamento deve ser maior que zero.'; END IF;


END$$

USE `banco_campo`$$
CREATE DEFINER = CURRENT_USER TRIGGER `banco_campo`.`Ativo_BEFORE_INSERT` BEFORE INSERT ON `Ativo` FOR EACH ROW
BEGIN
IF NEW.qtde <= 0 THEN SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'Erro: A quantidade do item de patrimônio deve ser maior que zero.';
END IF;


IF NEW.valor < 0 THEN SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'Erro: O valor do item de patrimônio não pode ser negativo.'; END IF;

END$$

USE `banco_campo`$$
CREATE DEFINER = CURRENT_USER TRIGGER `banco_campo`.`Ativo_BEFORE_UPDATE` BEFORE UPDATE ON `Ativo` FOR EACH ROW
BEGIN
IF NEW.qtde < 0 THEN SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'Erro: Não é permitido alterar a quantidade do patrimônio para valor negativo.';
END IF;


IF NEW.valor < 0 THEN SIGNAL SQLSTATE '45000'

SET MESSAGE_TEXT = 'Erro: Não é permitido alterar o valor do patrimônio para um valor negativo.';
END IF;

END$$

USE `banco_campo`$$
CREATE DEFINER = CURRENT_USER TRIGGER `banco_campo`.`SaldoAtivo_BEFORE_INSERT` BEFORE INSERT ON `SaldoAtivo` FOR EACH ROW
BEGIN
IF NEW.qtde < 0 THEN SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'Erro: O saldo de quantidade do item não pode ser negativo.'; END IF;

END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
